

def high(x):
        return {'add_reactions': x.add_reactions, 'administrator': x.administrator, 'attach_files': x.attach_files,
                'ban_members': x.ban_members, 'change_nickname': x.change_nickname, 'connect': x.connect,
                'create_expressions': x.create_expressions, 'create_instant_invite': x.create_instant_invite,
                'create_private_threads': x.create_private_threads, 'create_public_threads': x.create_public_threads,
                'deafen_members': x.deafen_members, 'embed_links': x.embed_links, 'external_emojis': x.external_emojis,
                'external_stickers': x.external_stickers, 'kick_members': x.kick_members,
                'manage_channels': x.manage_channels, 'manage_emojis': x.manage_emojis,
                'manage_emojis_and_stickers': x.manage_emojis_and_stickers, 'manage_events': x.manage_events,
                'manage_expressions': x.manage_expressions, 'manage_guild': x.manage_guild,
                'manage_messages': x.manage_messages, 'manage_nicknames': x.manage_nicknames,
                'manage_permissions': x.manage_permissions, 'manage_roles': x.manage_roles,
                'manage_threads': x.manage_threads, 'manage_webhooks': x.manage_webhooks,
                'mention_everyone': x.mention_everyone, 'moderate_members': x.moderate_members,
                'move_members': x.move_members, 'mute_members': x.mute_members, 'priority_speaker': x.priority_speaker,
                'read_message_history': x.read_message_history, 'read_messages': x.read_messages,
                'request_to_speak': x.request_to_speak, 'send_messages': x.send_messages,
                'send_messages_in_threads': x.send_messages_in_threads, 'send_tts_messages': x.send_tts_messages,
                'send_voice_messages': x.send_voice_messages, 'speak': x.speak, 'stream': x.stream,
                'use_application_commands': x.use_application_commands,
                'use_embedded_activities': x.use_embedded_activities,
                'use_external_emojis': x.use_external_emojis, 'use_external_sounds': x.use_external_sounds,
                'use_external_stickers': x.use_external_stickers, 'use_soundboard': x.use_soundboard,
                'use_voice_activation': x.use_voice_activation, 'value': x.value, 'view_audit_log': x.view_audit_log,
                'view_channel': x.view_channel, 'view_guild_insights': x.view_guild_insights}


def mid(x):
        return {'add_reactions': x.add_reactions, 'administrator': x.administrator, 'attach_files': x.attach_files,
                'ban_members': x.ban_members, 'change_nickname': x.change_nickname, 'connect': x.connect,
                'create_expressions': x.create_expressions, 'create_instant_invite': x.create_instant_invite,
                'create_private_threads': x.create_private_threads, 'create_public_threads': x.create_public_threads,
                'deafen_members': x.deafen_members, 'embed_links': x.embed_links, 'external_emojis': x.external_emojis,
                'external_stickers': x.external_stickers, 'kick_members': x.kick_members,
                'manage_channels': x.manage_channels, 'manage_emojis': x.manage_emojis,
                'manage_emojis_and_stickers': x.manage_emojis_and_stickers, 'manage_events': x.manage_events,
                'manage_expressions': x.manage_expressions, 'manage_guild': x.manage_guild,
                'manage_messages': x.manage_messages, 'manage_nicknames': x.manage_nicknames,
                'manage_permissions': x.manage_permissions, 'manage_roles': x.manage_roles,
                'manage_threads': x.manage_threads, 'manage_webhooks': x.manage_webhooks,
                'mention_everyone': x.mention_everyone, 'moderate_members': x.moderate_members,
                'move_members': x.move_members, 'mute_members': x.mute_members, 'priority_speaker': x.priority_speaker,
                'read_message_history': x.read_message_history, 'read_messages': x.read_messages,
                'request_to_speak': x.request_to_speak, 'send_messages': x.send_messages,
                'send_messages_in_threads': x.send_messages_in_threads, 'send_tts_messages': x.send_tts_messages,
                'send_voice_messages': x.send_voice_messages, 'speak': x.speak, 'stream': x.stream,
                'use_application_commands': x.use_application_commands,
                'use_embedded_activities': x.use_embedded_activities,
                'use_external_emojis': x.use_external_emojis, 'use_external_sounds': x.use_external_sounds,
                'use_external_stickers': x.use_external_stickers, 'use_soundboard': x.use_soundboard,
                'use_voice_activation': x.use_voice_activation, 'value': x.value, 'view_audit_log': x.view_audit_log,
                'view_channel': x.view_channel, 'view_guild_insights': x.view_guild_insights}


def low(x):
        return {'add_reactions': x.add_reactions, 'administrator': x.administrator, 'attach_files': x.attach_files,
                'ban_members': x.ban_members, 'change_nickname': x.change_nickname, 'connect': x.connect,
                'create_expressions': x.create_expressions, 'create_instant_invite': x.create_instant_invite,
                'create_private_threads': x.create_private_threads, 'create_public_threads': x.create_public_threads,
                'deafen_members': x.deafen_members, 'embed_links': x.embed_links, 'external_emojis': x.external_emojis,
                'external_stickers': x.external_stickers, 'kick_members': x.kick_members,
                'manage_channels': x.manage_channels, 'manage_emojis': x.manage_emojis,
                'manage_emojis_and_stickers': x.manage_emojis_and_stickers, 'manage_events': x.manage_events,
                'manage_expressions': x.manage_expressions, 'manage_guild': x.manage_guild,
                'manage_messages': x.manage_messages, 'manage_nicknames': x.manage_nicknames,
                'manage_permissions': x.manage_permissions, 'manage_roles': x.manage_roles,
                'manage_threads': x.manage_threads, 'manage_webhooks': x.manage_webhooks,
                'mention_everyone': x.mention_everyone, 'moderate_members': x.moderate_members,
                'move_members': x.move_members, 'mute_members': x.mute_members, 'priority_speaker': x.priority_speaker,
                'read_message_history': x.read_message_history, 'read_messages': x.read_messages,
                'request_to_speak': x.request_to_speak, 'send_messages': x.send_messages,
                'send_messages_in_threads': x.send_messages_in_threads, 'send_tts_messages': x.send_tts_messages,
                'send_voice_messages': x.send_voice_messages, 'speak': x.speak, 'stream': x.stream,
                'use_application_commands': x.use_application_commands,
                'use_embedded_activities': x.use_embedded_activities,
                'use_external_emojis': x.use_external_emojis, 'use_external_sounds': x.use_external_sounds,
                'use_external_stickers': x.use_external_stickers, 'use_soundboard': x.use_soundboard,
                'use_voice_activation': x.use_voice_activation, 'value': x.value, 'view_audit_log': x.view_audit_log,
                'view_channel': x.view_channel, 'view_guild_insights': x.view_guild_insights}
